language: ruby

before_install:
  - gem install bundler

cache:
  directories:
    - bundle

rvm:
  - 2.5.3

jobs:
  include:
    - stage: execute danger
      if: type = pull_request
      script: bundle exec danger
