# Fastlane automation for giggles

before_all do
end

desc('Execute All Rake Tasks')
lane :pipeline do
  sh('bundle exec rake spec')
end

after_all do
  next unless is_ci?

  danger
  slack(
    message: 'CI Successfully Completed',
    channel: '#johnny-junk-drawer', # Optional, by default will post to the default channel configured for the POST URL.
    success: true, # Optional, defaults to true.
    payload: { # Optional, lets you specify any number of your own Slack attachments.
      'Build Date' => Time.new.to_s,
      'Built by' => 'GitHub Actions'
    },
    default_payloads: [:git_branch, :git_author], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
    # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit`, `last_git_commit_hash`.
    attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
      # This hash is deep merged with the existing properties set using the other properties above. This allows your own fields properties to be appended to the existing fields that were created using the `payload` property for instance.
      # thumb_url: "http://example.com/path/to/thumb.png",
      fields: [{
        title: "My Field",
        value: "My Value",
        short: true
      }]
    }
  )
end

error do |_lane, error|
  next unless is_ci?

  slack(
    success: false,
    message: error
  )
end
