# Fastlane automation for giggles

before_all do
end

desc('Execute All Rake Tasks')
lane :pipeline do
  sh('bundle exec rake spec')
end

after_all do
  next unless is_ci?

  danger
  slack(
    message: 'CI Successfully Completed',
    channel: '#johnny-junk-drawer',
    payload: {
      'Build Date' => Time.new.to_s,
      'Built by' => 'GitHub Actions'
    },
    default_payloads: [:lane, :last_git_commit_hash, :git_branch, :git_author],
    attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
      # thumb_url: "http://example.com/path/to/thumb.png",
      fields: [{
        title: "My Field",
        value: "My Value",
        short: true
      }]
    }
  )
end

error do |_lane, error|
  next unless is_ci?

  slack(
    success: false,
    message: error
  )
end
