name: Pull Request Build & Test 

on: 
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Bundler
      run: gem install bundler
    - name: Bundle Install
      run: bundle install
    - name: Google Cloud Platform (GCP) CLI - gcloud
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: danger-sentiment
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    - name: Run Tests for PR
      run: bundle exec fastlane pipeline --verbose
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
        PROJECT_ID: danger-sentiment
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}